apiVersion: apps/v1
kind: Deployment
metadata:
  name: $CI_PROJECT_NAME
spec:
  selector:
    matchLabels:
      app: $CI_PROJECT_NAME
  replicas: 2
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: $CI_PROJECT_NAME
    spec:
      imagePullSecrets:
      - name: $RC_REGISTRY_PULL_SECRET
      containers:
      - name: $CI_PROJECT_NAME
        image: $RC_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_SHA
        imagePullPolicy: Always
        env:
          - name: NODE_ENV
            value: production
          - name: RC_INGRESS_HOSTNAME
            value: $INGRESS_HOSTNAME
        ports:
          - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 15
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 3
